
Fatal error: Uncaught exception 'Zend_Controller_Action_Exception' with message 'Action "error404" does not exist and was not trapped in __call()' in /var/www/mediam/library/Zend/Controller/Action.php:485
Stack trace:
#0 /var/www/mediam/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('error404Action', Array)
#1 /var/www/mediam/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('error404Action')
#2 /var/www/mediam/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /var/www/mediam/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /var/www/mediam/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /var/www/mediam/public/index.php(73): Zend_Application->run()
#6 {main}
  thrown in /var/www/mediam/library/Zend/Controller/Action.php on line 485
